#! /usr/bin/env bash

PWD=$(pwd)
CONFIG_DIR=$PWD/c_src/config

if [ -e $CONFIG_DIR/config.h ]; then
    echo "scrypt already configured"
    exit 0
fi

## Operate out of the scrypt config dir
## (This is obviously a hack, 
## and the configure script expects relative paths)
(cd $CONFIG_DIR && exec $CONFIG_DIR/configure) >

## Copy config.h to current dir. 
## This config file will be removed during rebar post hooks
cp $CONFIG_DIR/config.h $PWD
